using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using instore_optima.Infrastructure.Data;
using instore_optima.Domain.Entities;

namespace instore_optima.Api.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class OrdersController : ControllerBase
    {
        private readonly AppDbContext _context;

        public OrdersController(AppDbContext context)
        {
            _context = context;
        }

        // ?? GET ALL ORDERS
        [HttpGet]
        public async Task<IActionResult> GetOrders()
        {
            var orders = await _context.Orders.ToListAsync();
            return Ok(orders);
        }

        // ?? GET ORDER BY ID
        [HttpGet("{id}")]
        public async Task<IActionResult> GetOrder(int id)
        {
            var order = await _context.Orders
                .FirstOrDefaultAsync(o => o.OrderId == id);

            if (order == null) return NotFound();

            return Ok(order);
        }

        // ?? CREATE ORDER
        [HttpPost]
        public async Task<IActionResult> CreateOrder(Orders order)
        {
            // Validation
            if (order.UserId <= 0)
                return BadRequest("UserId is required and must be greater than 0");

            // Check if User exists (FK validation)
            var userExists = await _context.Users.AnyAsync(u => u.UserId == order.UserId);
            if (!userExists)
                return BadRequest($"User with ID {order.UserId} does not exist");

            // Reset OrderId (identity column - auto-generated by DB)
            order.OrderId = 0;

            // Set defaults
            order.OrderDate = DateTime.Now;
            order.Status = "Pending";

            if (order.TotalAmount == null)
                order.TotalAmount = 0;

            try
            {
                _context.Orders.Add(order);
                await _context.SaveChangesAsync();
                return CreatedAtAction(nameof(GetOrder), new { id = order.OrderId }, order);
            }
            catch (DbUpdateException ex)
            {
                return BadRequest("Error creating order: " + ex.InnerException?.Message);
            }
        }

        // ?? UPDATE ORDER STATUS (CONTROLLED)
        [HttpPut("{id}/status")]
        public async Task<IActionResult> UpdateOrderStatus(int id, [FromBody] string status)
        {
            var order = await _context.Orders.FindAsync(id);
            if (order == null) return NotFound();

            // ?? VALID STATUS LIST
            var validStatuses = new[] { "Pending", "Processing", "Shipped", "Delivered", "Cancelled" };

            if (!validStatuses.Contains(status))
                return BadRequest("Invalid status");

            // ?? BUSINESS RULE: cannot change delivered order
            if (order.Status == "Delivered")
                return BadRequest("Delivered order cannot be modified");

            order.Status = status;

            await _context.SaveChangesAsync();
            return Ok(order);
        }

        // ?? CANCEL ORDER (BUSINESS ACTION)
        [HttpPut("{id}/cancel")]
        public async Task<IActionResult> CancelOrder(int id)
        {
            var order = await _context.Orders.FindAsync(id);
            if (order == null) return NotFound();

            // ?? BUSINESS RULES
            if (order.Status == "Shipped" || order.Status == "Delivered")
            {
                return BadRequest("Order cannot be cancelled after shipping");
            }

            if (order.Status == "Cancelled")
            {
                return BadRequest("Order already cancelled");
            }

            order.Status = "Cancelled";

            await _context.SaveChangesAsync();
            return Ok(order);
        }

        // ?? DELETE ORDER (OPTIONAL — USE CAREFULLY)
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteOrder(int id)
        {
            var order = await _context.Orders.FindAsync(id);
            if (order == null) return NotFound();

            // ?? Allow delete only if not processed
            if (order.Status != "Pending")
            {
                return BadRequest("Only pending orders can be deleted");
            }

            _context.Orders.Remove(order);
            await _context.SaveChangesAsync();

            return Ok("Order deleted");
        }
    }
}
