// IReceiptRepository — contract for managing Receipt records.
// Receipts are auto-generated by PaymentRepository when a payment is marked "Completed".
// They serve as the customer-facing proof of payment and are ordered newest first.
using instore_optima.Domain.Entities;

namespace instore_optima.Domain.Interfaces
{
    public interface IReceiptRepository
    {
        /// <summary>Returns all receipts, ordered by generation date descending.</summary>
        Task<IEnumerable<Receipt>> GetAllReceiptsAsync();

        /// <summary>Returns a single receipt by its primary key. Returns null if not found.</summary>
        Task<Receipt?> GetReceiptByIdAsync(int receiptId);

        /// <summary>Returns the receipt linked to a specific payment. Returns null if no receipt exists yet.</summary>
        Task<Receipt?> GetReceiptByPaymentIdAsync(int paymentId);

        /// <summary>Persists a new receipt. GeneratedAt is always set server-side.</summary>
        Task<Receipt> CreateReceiptAsync(Receipt receipt);

        /// <summary>Updates an existing receipt record (e.g. to correct amount or dates).</summary>
        Task<Receipt> UpdateReceiptAsync(Receipt receipt);
    }
}