using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace instore_optima.Domain.Entities
{
    // DB Entity — an in-app alert delivered to a specific user.
    // Notifications are generated by the system for events such as low stock,
    // order status changes, or replenishment approvals.
    public class Notification
    {
        public int NotificationId { get; set; }

        public int UserId { get; set; } // FK → User who should receive this notification

        public string Message { get; set; } // plain-English text displayed to the user
        public string Type { get; set; }    // category of the notification, e.g. "LowStock", "OrderUpdate"
        public string Status { get; set; }  // e.g. "Unread", "Read", "Dismissed"
        public bool IsRead { get; set; }    // true once the user has opened/acknowledged the notification

        public DateTime CreatedAt { get; set; } // when the notification was generated
        public DateTime? ReadAt { get; set; }   // timestamp when the user marked it as read; null if still unread
    }
}
