// AUTO-GENERATED by EF Core tooling — do not hand-edit this file.
// Adds SenderDisplayName and SenderDisplayEmail (both nullable) columns to InternalMessages
// so that the sender's human-readable name and email can be stored directly on the message.

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace instore_optima.Api.Migrations
{
    /// <inheritdoc />
    public partial class AddSenderDisplayToInternalMessage : Migration
    {
        // Applies the schema change
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "SenderDisplayEmail",
                table: "InternalMessages",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "SenderDisplayName",
                table: "InternalMessages",
                type: "nvarchar(max)",
                nullable: true);
        }

        // Reverts the schema change
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "SenderDisplayEmail",
                table: "InternalMessages");

            migrationBuilder.DropColumn(
                name: "SenderDisplayName",
                table: "InternalMessages");
        }
    }
}
