// AUTO-GENERATED by EF Core tooling — do not hand-edit this file.
// Empty placeholder migration (InitialCreated) — no schema changes are applied or reverted.

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace instore_optima.Api.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreated : Migration
    {
        // Applies the schema change
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        // Reverts the schema change
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
