// AUTO-GENERATED by EF Core tooling — do not hand-edit this file.
// Adds TOTP (Time-based One-Time Password) support to the Users table (TotpEnabled flag and
// TotpSecret column) and a Purpose column to UserOtps to distinguish between different OTP
// use-cases (e.g. login 2FA vs. password reset).

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace instore_optima.Api.Migrations
{
    /// <inheritdoc />
    public partial class AddTotpAndOtpPurpose : Migration
    {
        // Applies the schema change
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "TotpEnabled",
                table: "Users",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<string>(
                name: "TotpSecret",
                table: "Users",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Purpose",
                table: "UserOtps",
                type: "nvarchar(max)",
                nullable: false,
                defaultValue: "");
        }

        // Reverts the schema change
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "TotpEnabled",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "TotpSecret",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "Purpose",
                table: "UserOtps");
        }
    }
}
