// AUTO-GENERATED by EF Core tooling — do not hand-edit this file.
// Adds an AttachmentsJson (nullable) column to InternalMessages to store serialized file
// attachment metadata alongside a message.

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace instore_optima.Api.Migrations
{
    /// <inheritdoc />
    public partial class AddAttachmentsJson : Migration
    {
        // Applies the schema change
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "AttachmentsJson",
                table: "InternalMessages",
                type: "nvarchar(max)",
                nullable: true);
        }

        // Reverts the schema change
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "AttachmentsJson",
                table: "InternalMessages");
        }
    }
}
