// AUTO-GENERATED by EF Core tooling — do not hand-edit this file.
// Adds a GrnNumber (Goods Receipt Note number) column and a DeliveredAt timestamp column
// to the PurchaseOrders table to track delivery confirmation details.

using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace instore_optima.Api.Migrations
{
    /// <inheritdoc />
    public partial class AddGrnToPurchaseOrder : Migration
    {
        // Applies the schema change
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<DateTime>(
                name: "DeliveredAt",
                table: "PurchaseOrders",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "GrnNumber",
                table: "PurchaseOrders",
                type: "nvarchar(max)",
                nullable: true);
        }

        // Reverts the schema change
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "DeliveredAt",
                table: "PurchaseOrders");

            migrationBuilder.DropColumn(
                name: "GrnNumber",
                table: "PurchaseOrders");
        }
    }
}
