// AUTO-GENERATED by EF Core tooling — do not hand-edit this file.
// Adds ActionType and ActionPayload (both nullable) columns to InternalMessages to allow
// messages to carry structured action data (e.g. approval requests or task notifications).

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace instore_optima.Api.Migrations
{
    /// <inheritdoc />
    public partial class AddActionFieldsToInternalMessage : Migration
    {
        // Applies the schema change
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "ActionPayload",
                table: "InternalMessages",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "ActionType",
                table: "InternalMessages",
                type: "nvarchar(max)",
                nullable: true);
        }

        // Reverts the schema change
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "ActionPayload",
                table: "InternalMessages");

            migrationBuilder.DropColumn(
                name: "ActionType",
                table: "InternalMessages");
        }
    }
}
